main.datasource.url=jdbc:hsqldb:file:.jmix/hsqldb/sciencealive
main.datasource.username=sa
main.datasource.password=

main.liquibase.change-log=kr/sciencealive/liquibase/changelog.xml

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=kr/sciencealive/menu.xml
jmix.ui.composite-menu=false

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin

jmix.core.available-locales=ko,en

server.port=${PORT:8080}
vaadin.launch-browser=false

logging.level.io.jmix=info
logging.level.liquibase=warn
logging.level.kr.sciencealive=info
jmix.eclipselink.use-inner-join-in-condition=true
